export default [
  { name: 'Home', path: '/', breakpoint: 'desktop' },
  { name: 'Getting Started', path: '/getting-started', breakpoint: 'tablet' },
  { name: 'Primitives', path: '/primitives', breakpoint: 'tablet' },
  { name: 'Palette', path: '/palette', breakpoint: 'tablet' },
  { menu: 'Typography', name: 'Blockquote', path: '/typography/blockquote', breakpoint: 'tablet' },
  { menu: 'Typography', name: 'Code', path: '/typography/code', breakpoint: 'tablet' },
  { menu: 'Typography', name: 'Heading', path: '/typography/heading', breakpoint: 'tablet' },
  { menu: 'Typography', name: 'Link', path: '/typography/link', breakpoint: 'tablet' },
  { menu: 'Typography', name: 'List', path: '/typography/list', breakpoint: 'tablet' },
  { menu: 'Typography', name: 'Paragraph', path: '/typography/paragraph', breakpoint: 'tablet' },
  { menu: 'Typography', name: 'Text', path: '/typography/text', breakpoint: 'tablet' },
  { menu: 'Layout', name: 'Columns', path: '/layout/columns', breakpoint: 'tablet' },
  { menu: 'Layout', name: 'Container', path: '/layout/container' },
  { menu: 'Layout', name: 'LayoutSet', path: '/layout/layoutset', breakpoint: 'tablet' },
  { menu: 'Layout', name: 'Pane', path: '/layout/pane', breakpoint: 'tablet' },
  { menu: 'Components', name: 'ActionButtons', path: '/components/actionbuttons', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Alert', path: '/components/alert', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Avatar', path: '/components/avatar', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Badge', path: '/components/badge', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Button', path: '/components/button', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Breadcrumb', path: '/components/breadcrumb', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Callout', path: '/components/callout', breakpoint: 'tablet' },
  { menu: 'Components', name: 'CalloutOverlay', path: '/components/calloutoverlay', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Card', path: '/components/card', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Dialog', path: '/components/dialog', breakpoint: 'tablet' },
  { menu: 'Components', name: 'DialogModal', path: '/components/dialogmodal', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Divider', path: '/components/divider', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Icon', path: '/components/icon', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Image', path: '/components/image', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Markdown', path: '/components/markdown', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Menu', path: '/components/menu', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Navigation', path: '/components/navigation', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Popover', path: '/components/popover', breakpoint: 'tablet' },
  { menu: 'Components', name: 'ProgressBar', path: '/components/progressbar', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Rating', path: '/components/rating', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Spinner', path: '/components/spinner', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Table', path: '/components/table', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Tabs', path: '/components/tabs', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Tag', path: '/components/tag', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Timeline', path: '/components/timeline', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Toast', path: '/components/toast', breakpoint: 'tablet' },
  { menu: 'Components', name: 'Tooltip', path: '/components/tooltip', breakpoint: 'tablet' },
  { menu: 'Form', name: 'Checkbox', path: '/form/checkbox', breakpoint: 'tablet' },
  { menu: 'Form', name: 'FieldSet', path: '/form/fieldset', breakpoint: 'tablet' },
  { menu: 'Form', name: 'FieldWrapper', path: '/form/fieldwrapper', breakpoint: 'tablet' },
  { menu: 'Form', name: 'Input', path: '/form/input', breakpoint: 'tablet' },
  { menu: 'Form', name: 'Label', path: '/form/label', breakpoint: 'tablet' },
  { menu: 'Form', name: 'Radio', path: '/form/ra  dio', breakpoint: 'tablet' },
  { menu: 'Form', name: 'RadioGroup', path: '/form/radiogroup', breakpoint: 'tablet' },
  { menu: 'Form', name: 'Select', path: '/form/select', breakpoint: 'tablet' },
  { menu: 'Form', name: 'SelectMenu', path: '/form/selectmenu', breakpoint: 'tablet' },
  { menu: 'Form', name: 'Switch', path: '/form/switch', breakpoint: 'tablet' },
  { menu: 'Form', name: 'Textarea', path: '/form/textarea', breakpoint: 'tablet' },
  { menu: 'Form', name: 'Usage with form libraries', path: '/form/usage-with-form-libraries', breakpoint: 'tablet' },
  { menu: 'Utilities', name: 'Backdrop', path: '/utils/backdrop', breakpoint: 'tablet' },
  { menu: 'Utilities', name: 'Group', path: '/utils/group', breakpoint: 'tablet' },
  { menu: 'Utilities', name: 'Hidden', path: '/utils/hidden', breakpoint: 'tablet' },
  { menu: 'Utilities', name: 'Modal', path: '/utils/modal', breakpoint: 'tablet' },
  { menu: 'Utilities', name: 'Overlay', path: '/utils/overlay', breakpoint: 'tablet' },
  { menu: 'Utilities', name: 'Portal', path: '/utils/portal', breakpoint: 'tablet' },
  { menu: 'Utilities', name: 'Set', path: '/utils/set', breakpoint: 'tablet' },
  { menu: 'Utilities', name: 'Sidebar', path: '/utils/sidebar', breakpoint: 'tablet' },
  { menu: 'Templates', name: 'Content', path: '/templates/page-content', breakpoint: 'fullHD', isBeta: true },
  {
    menu: 'Templates',
    name: 'Sidebar',
    path: '/templates/page-with-sidebar',
    breakpoint: 'desktop',
    isBeta: true
  },
  { menu: 'Styling & Theming', name: 'Theming', path: '/styling/theming', breakpoint: 'tablet' },
  { menu: 'Styling & Theming', name: 'Global styles', path: '/styling/global-styles', breakpoint: 'tablet' },
  { menu: 'Styling & Theming', name: 'CSS props', path: '/styling/css-props', breakpoint: 'tablet' },
  { menu: 'Styling & Theming', name: 'Styled components', path: '/styling/styled-components', breakpoint: 'tablet' },
  { menu: 'Styling & Theming', name: 'Fonts', path: '/styling/fonts', breakpoint: 'tablet' },
  { menu: 'Styling & Theming', name: 'Spacing', path: '/styling/spacing', breakpoint: 'tablet' },
  { menu: 'Styling & Theming', name: 'Visiblity', path: '/styling/visibility', breakpoint: 'tablet' },
  { name: 'Component Status', path: '/component-status', breakpoint: 'tablet' }
];
